### ISSUE TITLE
[LITTLE BUG] Same markdown => Result at two places rendered differently!

### ISSUE THREAD

**Issue by nhwCoder** [zhaouv/vscode-markdown-everywhere#11]
I use in a Python program the same source-markdown at two places but it is different rendered (see attached image)
Setting is preview-mode: Ignored

See attached image
* The two green source-markdown parts are identically GREEN(1) above and below

RESULT (red numbers)
* RED(1) and RED(2) are rendered differently, but RED(2) should look same as RED(1) with the last list entry indented.
* RED(3) is the default Python help from VSC and this is also rendered correct like RED(1)

Empty spaces in markdown should normally not influence/change the rendering result.
![issue_markdown](https://github.com/zhaouv/vscode-markdown-everywhere/assets/125078667/26f39555-b36d-4eca-89ee-08697a22e657)

**Comment by zhaouv** [comment]
This rule is the only rules which has free `\\s*` in `whileRegExp` (`free` means no other symbols after this). The preview part firstly remove all whileRegExp, then regard the remain content as markdown. So all indent will be removed for this rule. To fix this, the preview part will have to regard this rule as a special rule, but it will still do not support custom rules which similar to this. It is a known question, but I have not thought a general way to solve it. And I do not want to write a special case for only this rule. I will fix it when I find a general way.
```json
    {
        "name": "whitespace-triple-quote",
        "beginRegExp": "\\s+\"\"\" ?",
        "whileRegExp": "\\s*(?!\\s|\"\"\")",
        "whileSymbol": " ",
        "endRegExp": "\\s*\"\"\" ?",
        "example": "def abc():<br>&nbsp;&nbsp;&nbsp;&nbsp;\"\"\"<br>&nbsp;&nbsp;&nbsp;&nbsp;xxx xxx<br>&nbsp;&nbsp;&nbsp;&nbsp;xxx xxx<br>&nbsp;&nbsp;&nbsp;&nbsp;\"\"\"<br>&nbsp;&nbsp;&nbsp;&nbsp;...",
        "languages": [
            {"name":"julia","source":"source.julia"},
            {"name":"python","source":"source.python"}
        ]
    }
```
