### ISSUE TITLE
[Feature request] Option to export generated markdown

### ISSUE THREAD

**Issue by cdfa** [zhaouv/vscode-markdown-everywhere#12]
Thanks for this extension! It's really cool!
Can we get a command to export the generated markdown to a `.md` file?
That would be great for sharing the code outside of vscode, for example on github.

**Comment by zhaouv** [comment]
The next version will try add the feature **Extract Markdown**, which convert the selected portion into Markdown format according to the rules and settings, place it into the clipboard.

**Comment by cdfa** [comment]
Thanks! I will look into the other features i suggested when I find some time.
