### ISSUE TITLE
Disable code encapsulation in `<details>`.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [zhaouv/vscode-markdown-everywhere#18]
It looks dreadful:

> ![Screenshot_20240629_140352](https://github.com/zhaouv/vscode-markdown-everywhere/assets/42837531/fdcdb76c-110e-42ae-9595-1bcd45220c40)

but would be perfect if the `<pre>` was merely not encapsulated inside a `<details>` section. Consequently, how can I disable this?

**Comment by zhaouv** [comment]
settings.json - preview-mode - 'fenced'  
the showing-picture is 'folded' mode

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/18#issuecomment-2198212631

@zhaouv,

```JSONC
"markdown-everywhere.preview-mode": "fenced"
```

renders, as an example

```sh
#!/usr/bin/env sh

echo 'test'

# test time?!
```

mostly as I want, but not perfectly:

> ![image](https://github.com/zhaouv/vscode-markdown-everywhere/assets/42837531/c3b38d28-0aab-42f0-9c38-af1cd165317c)

is that extra space below expected?
