### ISSUE TITLE
Render `YAML` front-matter (as `<table>` or `<pre>`).

### ISSUE THREAD

**Issue by roke-julian-lockhart** [zhaouv/vscode-markdown-everywhere#19]
Currently, it doesn't. All this would need to do is tell https://github.com/mjbvz/vscode-markdown-yaml-preamble.git to render. Otherwise, it should render as a code block so that it doesn't render as broken text.

**Comment by zhaouv** [comment]
I have no interest in implementing this feature

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/19#issuecomment-2198213007

@zhaouv, makes sense. I can't imagine this being used much.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/19#issuecomment-2198217947

@zhaouv, would having it render as a fenced code block instead be reasonable? I ask because otherwise, it appears as quite broken text.

**Comment by zhaouv** [comment]
it is embedded text, not a depend markdown file. these do not important.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/19#issuecomment-2198229066

@zhaouv, could you elaborate what you mean by this? The YAML preamble is a feature of most Markdown processors.

**Comment by zhaouv** [comment]
> it is embedded text, not a depend markdown file. these do not important.

`not a independ markdown file`. this extension work for markdown in comment. no front-matter for this case

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/19#issuecomment-2198417127

@zhaouv, that doesn't mean that it couldn't be embedded as the first comment. However, I understand - it wouldn't work if https://github.com/zhaouv/vscode-markdown-everywhere/issues/20#issue-2381741429 were implemented anyway, so it wouldn't be useful for most scripts.
