### ISSUE TITLE
Latex Support

### ISSUE THREAD

**Issue by githubpsyche** [zhaouv/vscode-markdown-everywhere#2]
Hi, thanks for the extension - have been looking for something like it for a long time.

I wonder how hard it would be to add some latex support to it? It looks like neither the syntax highlighter nor the markdown preview handle it. 

(Would be happy to help out with this, too, though I don't have much experience with VSCode Extension development.)

**Comment by zhaouv** [comment]
Thanks for catch. The `line rule with a start mark` of percentage somehow not working. You can use `line rule starts with the mark`. I will work for this bug.

![image](https://user-images.githubusercontent.com/26158289/105580090-4dcaaa00-5dc5-11eb-8272-5a9559726bd0.png)

**Comment by githubpsyche** [comment]
Oh sorry, I'm actually referring to the converse situation: where you're using LaTeX within Markdown. Github flavored Markdown supports enclosing mathematical expressions in dollar sign tags — eg `$\theta$` to convey $\theta$. Double dollar signs ($$) alternatively mark expressions that aren't inline. I use these a lot to document code with mathematical content. EDIT: Ah, it's not rendering after all here. But it would if I included the tags in a MD file in VSCode, as well as if I were using Markdown cells in Jupyter or IPython. I'm no longer sure whether the tags successfully enclose LaTeX in Markdown files I might host on Github.

**Comment by zhaouv** [comment]
You may want extension like [Markdown+Math](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath). It is not range of this extension.

**Comment by githubpsyche** [comment]
You might be right. Thanks again for all this; it's really done a lot to concentrate my work in a mature IDE. I'm telling anyone who'll listen about it. I really, sincerely think that this extension will have a huge impact on the Python community once people become aware of the kinds of workflows it enables.
