### ISSUE TITLE
Render the shebang (as a `<pre><code>`).

### ISSUE THREAD

**Issue by roke-julian-lockhart** [zhaouv/vscode-markdown-everywhere#20]
As https://gitlab.com/uramer/vscode-comments-as-markdown/-/issues/2 states:

<blockQuote>

Placing a `</pre>` after it doesn't work as a workaround, so this needs to be handled by the extension. It should become a code block:

~~~MD
```shebang
#!/usr/bin/env sh
```
~~~

...rather than inline:

```MD
`#!/usr/bin/env sh`
```

</blockQuote>

**Comment by zhaouv** [comment]
I have no interest in implementing this feature

**Comment by RokeJulianLockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/20#issuecomment-2198213058

:<

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/20#issuecomment-2198213058

@zhaouv, the reason that this matters is that otherwise, the shebang appears as body text. That's surely not right?

**Comment by zhaouv** [comment]
it is embedded text, not a depend markdown file. these do not important.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/20#issuecomment-2198229091

@zhaouv, it does still display the same, though... Perhaps if the shebang were ignored the processor, it would be sensical.

**Comment by zhaouv** [comment]
by the way you can do it with <https://github.com/zhaouv/vscode-markdown-everywhere#preview-inject> .  ref <https://github.com/zhaouv/vscode-markdown-everywhere/issues/17> write your own relpace statements

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/20#issuecomment-2203798001

Thanks, @zhaouv. If I can ascertain how to do it, I'll send a PR adding this as a default rule. However, I don't think I can understand any of that... The best I've come up with is a pathetic attempt:

```JSONC
{
	"language": "markdown",
	"path": ".*",
	"beforeSource":" </pre>"
}
```

...which solely covers the find aspect of an F&R. Apologies. XD
