### ISSUE TITLE
Syntax highlighting in comments doesn't work.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [zhaouv/vscode-markdown-everywhere#21]
I see https://github.com/zhaouv/vscode-markdown-everywhere/blob/672ff46b217ebb07edeaf4270cd6116356498737/README.md#markdown-everywhere that it's meant to, but it doesn't appear to for me:

> ![Screenshot_20240629_150738](https://github.com/zhaouv/vscode-markdown-everywhere/assets/42837531/6eabd5a5-2d33-4927-a878-f20c44dc9289)

**Comment by zhaouv** [comment]
the extension only works on the format in its settings e.g. `# MD xxxxx`

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/21#issuecomment-2198213693

@zhaouv, which preference do you refer to? `markdown-everywhere.preview-mode-language`?

**Comment by zhaouv** [comment]
https://github.com/zhaouv/vscode-markdown-everywhere#supported-list > `Example`

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/21#issuecomment-2198229913

@zhaouv, thanks. I see in https://github.com/zhaouv/vscode-markdown-everywhere/blob/672ff46b217ebb07edeaf4270cd6116356498737/README.md?plain=1#L142, https://github.com/zhaouv/vscode-markdown-everywhere/blob/672ff46b217ebb07edeaf4270cd6116356498737/README.md?plain=1#L145, https://github.com/zhaouv/vscode-markdown-everywhere/blob/672ff46b217ebb07edeaf4270cd6116356498737/README.md?plain=1#L147, and https://github.com/zhaouv/vscode-markdown-everywhere/blob/672ff46b217ebb07edeaf4270cd6116356498737/README.md?plain=1#L153 that the comments must be prefixed with `MD`. Can this be disabled? I'd like it to apply to all comments.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/zhaouv/vscode-markdown-everywhere/issues/21#issuecomment-2198244248

It appears that I've already discussed this in https://github.com/zhaouv/vscode-markdown-everywhere/issues/10#issuecomment-1867222283.
