### ISSUE TITLE
Syntax highlight issues with percent encoded triple quoted doc strings

### ISSUE THREAD

**Issue by dbrattli** [zhaouv/vscode-markdown-everywhere#24]
Thanks for the great plugin. I have some issues when using it with the [Jupytext Percent format] (https://jupytext.readthedocs.io/en/latest/formats-scripts.html) inside Python source files. The problem is when there is a `# %% [markdown]` in front of a multiline triple quoted markdown cell:

<img width="647" alt="Skjermbilde 2024-07-17 kl  11 25 59" src="https://github.com/user-attachments/assets/adf996c0-dd1d-4284-9a8b-d0cb7c48bd45">

As you can see the markdown is not highlighted correctly. Many Python keywords seem to be highlighted etc. If I remove the `# %% [markdown]` in front of the triple quoted markdown string (or put a line in between), then things are formatted correctly again:

<img width="616" alt="Skjermbilde 2024-07-17 kl  11 24 19" src="https://github.com/user-attachments/assets/2762417a-cd4c-4e8b-944c-9d2084bd9d64">

Below is the same code block as text:

```py
# %% [markdown]
"""
# Basic Type Annotations

For basic type annotations, we will cover annotating variables for basic
container types and simple functions.

In this post we will be using the function [reveal_type]
(https://docs.python.org/3/library/typing.html#typing.reveal_type) to
ask the static type checker to reveal the inferred type of its argument.

Most type checkers support reveal_type() even if the name is not
imported from typing. However, to avoid runtime errors it should be
imported from the typing module. At runtime, this function prints the
runtime type of its argument and returns the argument unchanged.
"""
```

Hope there is an easy fix for this. Thanks.

**Comment by zhaouv** [comment]
<img width="652" alt="image" src="https://github.com/user-attachments/assets/6da48cd4-9683-42b9-8eb3-7619d128bf22">
a known issue, the `"""` is regarded as comment, because it is the first line following the LRSM rule. still haven't figured out the mechanism

**Comment by zhaouv** [comment]
fixed

**Comment by dbrattli** [comment]
This is great news. Thanks for fixing 🥰 FYI: @Anitsirc22
