### ISSUE TITLE
The way to fix following first line wrongly highlighted as comment in LRSM

### ISSUE THREAD

**Issue by yoshioka-naoki** [zhaouv/vscode-markdown-everywhere#25]
About the comment in readme below on LRSM rule:
> There is bug for this case. The following first line will be highlighted as comment. I haven't figured out the mechanism yet. So please put a empty line after these.

This is solved by commenting out whole "if (getRuleType(rule) == LRSM) {..}" in generateGrammar.js.
But I don't know if it's Ok. Could you fix it in a right way?
```js
    let injectionAtom = s => 'L:' + s + ' -string -comment -meta.embedded.block.everywhere.md'
   // if (getRuleType(rule) == LRSM) {
   //     injectionAtom = s => 'L:' + s + ' -string -meta.embedded.block.everywhere.md'
   // }
```

**Comment by zhaouv** [comment]
`left` is `-string -comment`, `right` is `-string`.  
This change will fix the behavior in line 2 and line 6.  
However, the issue described in **issue2** still remains: if this `if` statement is commented out, LRSM will not work in some languages, such as LaTeX and MATLAB.

Anyway, it is a great discovery to identify that this target leads to the **"following first line bug"**.

A choice must be made: either give up LRSM support for some languages or accept the bug.

I will try to find a better way. If no good solution is found, it will roll back the fix of issue 2. The "following first line bug" is widespread in Python. LRSM of LaTeX and MATLAB seems not very useful.

![image](https://github.com/user-attachments/assets/28cf50f6-80df-497c-858d-31df9819e1e2)
![image](https://github.com/user-attachments/assets/032c76ec-4f3e-45f6-8cf4-6fed69ff873e)

**Comment by zhaouv** [comment]
sorry for forgetting put your id into changelog (will put in next version). how did you figure out it? @yoshioka-naoki

**Comment by yoshioka-naoki** [comment]
no problem.
As I only knew the problem is 
- textmate scope is updated
- "comment" is inserted
- it's specific to LRSM

I changed some codes it seems to be related, and finally found the causality above... not a smart way...
