### ISSUE TITLE
Support `number-sign-double-percentage` in more languages

### ISSUE THREAD

**Issue by MatrixRanger98** [zhaouv/vscode-markdown-everywhere#4]
I like this extension very much. But I should recommend `supporting number-sign-double-percentage` instead of other options in more languages. This is actually a standard way of declaring cells and writing markdown comments in scripts dating back to Eclipse and Spider IDE and is widely supported by many editors and tools including [Atom - Hydrogen](https://nteract.gitbooks.io/hydrogen/content/docs/Usage/Cells.html), [Jupytext](https://jupytext.readthedocs.io/en/latest/formats.html), Visual Studio - Python Tools and PyCharm alongside VSCode - Jupyter. This is called percent format according to [Jupytext](https://jupytext.readthedocs.io/en/latest/formats.html).

**Comment by zhaouv** [comment]
There is already `number-sign-double-percentage` rule for python [here](https://github.com/zhaouv/vscode-markdown-everywhere/blob/c502fb94c9796be6159cbd5da508bd461758a6ce/build/rules.js#L177),
which has format
```python
# %% [markdown]
# # highlight python markdown cell
# for the vscode-python data-science feature
```
In my impression `# %%` are splitters for cells, not signs for markdown cells. It should be appended `[markdown]` in python to declare markdown cell.

**Comment by MatrixRanger98** [comment]
Yes. It is already implemented but only for python and there are conflicts between this grammar and others. I use R and Julia a lot besides Python in Atom Hydrogen and often use Jupytext to translate the percent format scripts to rmarkdown and then have it compiled by knitr. The two tools mentioned above have this kind of markdown cell support for multiple languages. Since Atom community is not active any more, I am expecting extensions with similar features in VSCode.

**Comment by zhaouv** [comment]
it will work for all these languages next version in few days
```
coffeescript
dockerfile
git-commit
git-rebase
diff
ignore
properties
makefile
perl
perl6
powershell
python
r
ruby
shellscript
yaml
cython
julia
cmake
```
