### ISSUE TITLE
Support Syntax Highlighting of the file source language in the Embedded Preview

### ISSUE THREAD

**Issue by MatrixRanger98** [zhaouv/vscode-markdown-everywhere#5]
As the Markdown paragraphs are written as comments in scripts of a particular language, it is more comfortable to have the feature of syntax highlighting in preview for the entire file.

**Comment by zhaouv** [comment]
I can't understand `syntax highlighting in preview for the entire file`. Maybe you should describe it more. It seems similar with the fenced previewing mode.

**Comment by MatrixRanger98** [comment]
I mean you can add syntax highlighting in preview panel not only in the markdown chunk but also outside the chunk for the rest of the codes. It does not seem necessary as there is already highlighting in the editor but it would look more beautiful.

**Comment by zhaouv** [comment]
but in the fenced mode, the markdown has been rendered as html. the python code highlighted by fenced code. why it is not satisfying the require. maybe you can use something like 
Microsoft Word to change the color of code and show a picture of what you thought.
![](https://github.com/zhaouv/vscode-markdown-everywhere/raw/master/img_md/fenced-preview.png)
