### ISSUE TITLE
Rust support for triple slash comments

### ISSUE THREAD

**Issue by ciresnave** [zhaouv/vscode-markdown-everywhere#8]
Good morning!

Rust uses a triple slash at the beginning of doc comments.  Doc comments are interpreted as Markdown when the Rust code is sent to crates.io.  I'm trying to figure out how best to add a rule for triple slashes but so far my attempts to modify the double slash rule from vscode-markdown-everywhere's docs have failed.  I would assume adding triple slash support would be simple.  Can anyone suggest how to achieve it?  

Thanks!

**Comment by zhaouv** [comment]
I have not tested, this should work
```json
"markdown-everywhere.customized-rules": [
    "defaultRules",
    {
        "name": "triple-slash",
        "whileRegExp": "///",
        "example": "/// # title<br>/// content<br>",
        "languages": [
            { "name": "rust", "source": "source.rust" }
        ]
    }
]
```
or `{ "name": "Rust", "source": "source.Rust" }`

**Comment by ciresnave** [comment]
That's very similar to what I tried...but it leaves the extension just spinning its wheels and doing nothing.  I figured I must have done something wrong...but your rule does the same mine does.  The preview pane is empty and there is a moving line above it.  Nothing ever populates.

**Comment by ciresnave** [comment]
Initially, this didn't work.  Restarting VSCode didn't help.  Rebooting the whole PC made it work flawlessly.  Thank you!
